package com.example.aftas.enums;

public enum AuthorityEnum {

    GRANT_AUTHORITY_TO_ROLE,
    REVOKE_AUTHORITY_FROM_ROLE,
    ASSIGN_ROLE_TO_USER,
    CREATE_ROLE,
    UPDATE_ROLE,
    DELETE_ROLE,
    VIEW_ROLES,
    UPDATE_USERS,
    VIEW_USERS,
    DELETE_USERS,
    VIEW_AUTHORITIES,

    VIEW_LEVELS,
    VIEW_ONE_LEVEL,
    CREATE_LEVEL,
    UPDATE_LEVEL,
    DELETE_LEVEL,

    VIEW_FISHES,
    VIEW_ONE_FISH,
    CREATE_FISH,
    UPDATE_FISH,
    DELETE_FISH,

    VIEW_COMPETITIONS,
    VIEW_UPCOMING_COMPETITIONS,
    VIEW_MY_COMPETITIONS,
    VIEW_ONE_COMPETITION,
    CREATE_COMPETITION,
    DELETE_COMPETITION,

    VIEW_RANKING_BY_MEMBER_AND_COMPETITION,
    UPDATE_RANKING_BY_MEMBER_AND_COMPETITION,
    REGISTER_MEMBER_TO_COMPETITION,
    VIEW_TOP_3,

    VIEW_HUNTING_BY_COMPETITION,
    VIEW_HUNTING_BY_COMPETITION_AND_MEMBER,
    VIEW_ONE_HUNTING,
    CREATE_HUNTING,
    DELETE_HUNTING,
    UPDATE_HUNTING,



}